# Use the official Node.js image as the base image
FROM node:16

# Set working directory
WORKDIR /app

# Copy package.json and pnpm-lock.yaml to the working directory
COPY package.json pnpm-lock.yaml ./

# Install pnpm globally and dependencies
RUN npm install -g pnpm && pnpm install

# Set Puppeteer cache and installation path
ENV PUPPETEER_CACHE_DIR=/opt/render/.cache/puppeteer
ENV PUPPETEER_DOWNLOAD_PATH=/opt/render/.cache/puppeteer
ENV PUPPETEER_EXECUTABLE_PATH=/opt/render/.cache/puppeteer/chrome-linux/chrome

# Install Chromium directly to Puppeteer’s expected directory
RUN npx puppeteer install chrome

# Expose the application's port
EXPOSE 1000

# Copy the remaining application files to the working directory
COPY . .

# Start the application
CMD ["pnpm", "start"]
