services:
  - name: puppeteer-service
    type: web
    plan: free
    runtime: docker # Specify "docker" as the runtime since you're using a Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
    dockerfilePath: ./Dockerfile
    autoDeploy: true
